language: node_js
node_js:
  - "8"
  - "10"
  - "12"

install:
  - npm ci

cache:
  directories:
  - "$HOME/.npm"

script:
  - npm run validate --prod
  - npm run lint
  - npm run test

branches:
  only:
    - master
