language: node_js
node_js:
  - "12"
  - "14"
  - "16"

install:
  - npm ci

cache:
  directories:
  - "$HOME/.npm"

script:
  - npm install -g coveralls
  - npm run lint
  - npm run validate --prod
  - npm run test && nyc report --reporter=text-lcov | coveralls

branches:
  only:
    - master
